name: krezio_ai
description: "Krezio.ai - O futuro das suas finanças, guiado por dados."
publish_to: 'none'
version: 0.4.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  speech_to_text: ^7.0.0
  shared_preferences: ^2.3.3
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - models/on_device/krezio_nlp_model.json
    - models/voice/voice_manifest.json

